### ISSUE TITLE
Check-list 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/deployer#1]
- [x] local copy of a pre-defined list of 'epi-relevant CRAN packages' (see https://github.com/reconhub/deployer/issues/2)
- [ ] script to set up local CRAN as default repos
- [x] Rstudio for windows, mac, linux
- [ ] devel packages: sources and ideally git trees for RECON packages, and sources for some other devel packages, e.g. *ggplot2* and *plotly* 
- [ ] script to facilitate installation of devel packages

**Comment by richfitz** [comment]
There are systems (MRAN at least) that allow checkpointing a package back in time.  We could use that to grab things from (say) 6 months ago as well as the current lot from CRAN

**Comment by richfitz** [comment]
With reconhub packages, I think you'd possibly want to automate cloning the entire source tree and not just getting the current version into the repo

**Comment by thibautjombart** [comment]
@richfitz re automatic cloning of all trees of packages on reconhub: yes definitely but not all projects are packages, there are a few exceptions like the website, or this project here.

**Comment by richfitz** [comment]
Oh, I meant _for each package project_, you'd want to automate cloning of the whole source tree.  We can work out how to automatically derive the the list of packages using the github API

**Comment by thibautjombart** [comment]
Got you. I haven't played with *git2r* but surely it can clone stuff?

**Comment by richfitz** [comment]
Yeah, it can.  But cloning stuff is easy and if that's the only thing to do then it's probably just easier to shell out
