### ISSUE TITLE
Malformed URL error 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/deployer#10]
@richfitz  In an empty working directory (after `rm * -rf `), I get:
```
> nomad::build("reconhub/deployer", "deployer")
Error: Downloading 'https://github.com/reconhub/deployer/archive/.zip' failed with code 404
```

**Comment by richfitz** [comment]
This is fixed in the most recent provisionr - can you try upgrading please?

**Comment by thibautjombart** [comment]
Yes will try and report

**Comment by thibautjombart** [comment]
Looks like that was it. Now going through.
