### ISSUE TITLE
Clarification in README

### ISSUE THREAD

**Issue by jeskarp** [reconhub/deployer#14]
When people have been installing R with a deployer in workshops, a common issue/source of confusion is that in order for the `activate.R` script to work, the working directory needs to be in the deployer folder.

Can this be clarified in the README?

**Comment by zkamvar** [comment]
Probably the best solution for this would be to add an RStudio project file to the folder and tell the user to double-click on the RStudio project file itself and then open `activate.R` from RStudio.

**Comment by thibautjombart** [comment]
I was planning on this too. Can somebody create an `.Rproj` file using Rstudio and put it in `inst/`?

**Comment by thibautjombart** [comment]
@zkamvar if:

- there is now an `.Rproj` file we can open from Rstudio
- this is used in the README
- the README contains an alternative approach for non-Rstudio environments

Then please close this issue :)

**Comment by zkamvar** [comment]
> the README contains an alternative approach for non-Rstudio environments

Will fix.

**Comment by zkamvar** [comment]
Will fix later. Most will be using RStudio and those that don't will know better.
