### ISSUE TITLE
Problem downloading R studio

### ISSUE THREAD

**Issue by pbkeating** [reconhub/deployer#23]
@zkamvar I just tried to create a deployer and after downloading all the various packages and successful installation of R, I received the following error message when installing R studio

[1/4]  windows [ 1.17 kB in  0s ]Error: Downloading 'https://download1.rstudio.org/RStudio-1.2.1335-1.exe' failed with code 404

It seems RStudio-1.2.1335-1 is also a professional version of R Studio.

Sidenote: may be worth mentioning on the deployer vignette that good internet connection will be required for this process (although should be obvious considering the 1000+ packages to download) and that it will take some time.

**Comment by zkamvar** [comment]
Hi Pat,

This is because RStudio decided to change their URL for downloading the program. I've fixed this in a nomad branch:

you can install it with:

```r
remotes::install_github("reconhub/nomad@dash-it-all")
```

after that, you should be able to build the deployer correctly.

**Comment by zkamvar** [comment]
cf: https://github.com/reconhub/nomad/pull/18

**Comment by zkamvar** [comment]
I'm going to close this as it has been fixed on nomad, but please do reopen this if you run into the issue again.
