### ISSUE TITLE
Naming and package structure

### ISSUE THREAD

**Issue by richfitz** [reconhub/deployer#3]
At the moment we have at the base

* `provisionr` - does the basic dependency graph work and can sort out collecting packages up from non-CRAN locations

On top of that I see who things

* something that organises downloading and collecting everything into one place - that is what is currently implemented in this repo
* a `recon` specific set of packages, branding, documentation, etc

The general infrastructure package can live in this organisation if needed but it's not really specific to us.  It will also end up on CRAN shortly after `provisionr`.

Naming wise; if you want to keep the recon-specific part as `deployer` I would suggest the name `nomad` for the infrastructure bits (or I can fold it entirely into provisionr but I feel like it is a separate thing)

**Comment by thibautjombart** [comment]
Awesome - thanks a lot for this. No worries leaving the package in this organisation, RECON covers also '*general-purpose tools for data cleaning, versioning, and encryption*'.. ahem.. and package development and deployment. I'll add these bits to our pitch.

`nomad` sounds great, love it, and yes definitely regarding splitting the generic *vs* specific bits. I will discuss over tea regarding the `RECON` specific bits.

**Comment by richfitz** [comment]
This is resolved with the creation of the nomad package
