### ISSUE TITLE
404 error on rstudio download

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/deployer#33]
Running `nomad::build("reconhub/deployer", out_dir)` today I get:
```
Nomad: rstudio
[1/9]    windows => RStudio-1.3.959.exe        (163.5 Mb)                     
[2/9]      macos => RStudio-1.3.959.dmg        (141.7 Mb)                     
[3/9]     trusty [ 1.90 kB in  0s ]Error: Downloading 'https://download1.rstudio.org/desktop/trusty/amd64/rstudio-1.3.959-amd64.deb' failed with code 404
> 

```
@richfitz I think this is because the linux release name has changed from `trusty` to `xenial` (older one) and `bionic`. Not sure there is a nice easy way to determine these. What is your recommended fix?

**Comment by richfitz** [comment]
Looks like it needs a fix here: https://github.com/reconhub/nomad/blob/master/R/rstudio.R - though I see that xenial is listed there. Are you still on trusty?

**Comment by thibautjombart** [comment]
Thanks for the quick reply. I am on `bionic`: 
```bash
master@icarus:~$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by richfitz** [comment]
Right - looks like it is trying to download *all* of those binaries. Can you confirm on the last successful build? If so you'll just need to delete the trusty line (https://github.com/reconhub/nomad/blob/master/R/rstudio.R#L32) and things will probably just work

**Comment by thibautjombart** [comment]
Yup, that fixed it. And now I know where to look for these URLs. Thanks!
