### ISSUE TITLE
List devel packages to install

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/deployer#4]
In the form `[username]/[package]`; also indicate which ones:

- have `remotes`
- need compilation

**Comment by thibautjombart** [comment]
### RECON packages
- `reconhub/outbreaks`
- `reconhub/shinyHelpers`
- `reconhub/recon.ui`
- `reconhub/recontools`
- `reconhub/distcrete`
- `reconhub/incidence`
- `reconhub/incidence.ui`
- `reconhub/epicontacts`
- `reconhub/epicontacts.ui`
- `reconhub/epitrix`
- `reconhub/projections`
- `reconhub/earlyR`
- `reconhub/dibbler`
- `reconhub/outbreaker2`
- `reconhub/branchr`

### other github packages
- `tidyverse/ggplot2`
- `ropensci/plotly`

**Comment by thibautjombart** [comment]
### Packages with remotes
* `vimes`
* `shinyHelpers`
* `recon.ui`
* `incidence.ui`
* `epicontacts.ui`
* `outbreaker2`
* `epitrix`
* `earlyR`
* `projections`
* `recontools`

**Comment by thibautjombart** [comment]
### Packages requiring compilation

- `outbreaker2`

**Comment by thibautjombart** [comment]
@richfitz should be it - let me know how it goes

**Comment by richfitz** [comment]
This package: `ropensci/plotly` is likely to cause drama, no?  Is there a reason not to use the CRAN version for now?

**Comment by thibautjombart** [comment]
Yes it will, but the CRAN version is just not working with the CRAN ggplot2, and is used in incidence.ui. So in a nutshell it depends on whether we want incidence.ui to work, which I do. Note that this comes at a cost of functionality, as other bits of ggplot2 devel are broken.

**Comment by richfitz** [comment]
This does seem in your case like you're poisoning the well a bit.  Is it not possible to backport the bits of plotly into incidence.ui until the situation resolves itself?

**Comment by thibautjombart** [comment]
Like revert back to an older version that was working? Theoretically yes but I lost track of which version was working. Should be possible to find out though.

**Comment by richfitz** [comment]
I was more thinking, copy the bits from plotly that incidence.ui needs _into_ incidence.ui while the version turmoil persists (so that the dependency is on CRAN plotly only), or fork plotly onto reconhub and fix it up to the point where the dependency is on CRAN ggplot2
