### ISSUE TITLE
Empty dir error

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/deployer#9]
@richfitz  In an empty working directory (after `rm * -rf `), I get:
```
> nomad::build("reconhub/deployer", ".")
Error in nomad::build("reconhub/deployer", ".") : 
  'dest' must be an empty directory
```

**Comment by richfitz** [comment]
Is it actually empty?  `ls -a` perhaps?

**Comment by thibautjombart** [comment]
Yes, I did check that. It is. Fully. Nothing there. Gone. Pfiout. 

:)

**Comment by thibautjombart** [comment]
Right, so here is what happened: destination is the folder on which a usb stick is mounted; I wiped the device, umounted and remounted for good measure, but the mount added a .Trashxxx folder automatically, which then triggers the error. 

Not a bug, but a behaviour maybe best changing. Maybe add `ignore_hidden = TRUE` to ignore hidden folders by default?

**Comment by richfitz** [comment]
I'm not sure.  It's not empty, so I feel like the behaviour is correct.

**Comment by thibautjombart** [comment]
Sure, but is it a wanted behaviour in the first place? ;) 
I am not sure what other OSes do by default, but I suspect `.Trash` or similar folders will be frequently added to portable drives without the user necessarily knowing it. If the motivation for the error is avoiding removal of existing content, ignoring folders starting with `.` should be safe enough?

**Comment by richfitz** [comment]
yeah, avoiding trashing things (and dealing with inconsistent states #6) requires a level of directory hygiene.  Given my bandwidth for adding things to packages, working around weird shit that OS's do is not high up the list.

When I was setting up some big disks for docker to run on a VM, the general advice was to avoid the root directory.  So if you put everything in a subdirectory the problem would just go away

**Comment by thibautjombart** [comment]
Yes I agree it is healthier to dump files in a new directory. That isn't number 1 on the list of additional features I'd have anyway. Thanks for checking out.

**Comment by thibautjombart** [comment]
```
[1042/1045]                Zelig => Zelig_5.1.5.tgz                   (1.8 Mb)
[1043/1045]              zipcode => zipcode_1.0.tgz                   (862.3 Kb)
[1044/1045]                  zoo => zoo_1.8-1.tgz                     (883.6 Kb)
[1045/1045]                 zoom => zoom_2.0.4.tgz                    (31.7 Kb)
nomad: r
[1/3] windows => R-3.4.2-win.exe (74.5 Mb)                                    
Error: Downloading 'https://cloud.r-project.org/bin/macosx/old/R-3.4.2.pkg' failed with code 404
> 
```
